# Generated by Django 5.2 on 2025-04-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('stripe_customer_id', models.CharField(max_length=100, unique=True)),
                ('stripe_subscription_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
